spring.application.name=scheduler-service
server.port=8081

spring.quartz.properties.org.quartz.plugin.jobInitializer.class=org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
spring.quartz.properties.org.quartz.plugin.jobInitializer.failOnFileNotFound=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# application.properties (common - same interval fine across environments for now)
retry.poller.fixed-delay-ms=15000

logging.file.name=logs/scheduler-service.log